#!/bin/bash


### importa dados para o mysql

LOAD DATA INFILE '/absolute/path/data.csv' 
INTO TABLE tableName
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '/absolute/path/data.csv' 
INTO TABLE tableName
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;